---
controller_ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/ansible_provision_ed25519"
controller_bootstrap_state_dir: "{{ lookup('env', 'HOME') }}/.local/state/ansible-provisioning"

grafana_datasources:
  - name: Prometheus
    ds_type: prometheus
    ds_url: "http://192.168.0.0:9090"
    if_default: true

offworld_admin_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIjlxsmth7NgSzWToFAHqkwPue7oW+KCTFL3q1zPLl/7 colinJ-Desktop-Offworld-Admin-Test"