- name: Provision Machine
  hosts: monitoring_servers
  become: true
  vars:
    new_user: "offworld-admin"

  tasks:
  - name: Create Human User
    ansible.builtin.user:
      name: "{{ new_user }}"
      password: "{{ new_user_password | password_hash('sha512')}}"
      shell: /bin/bash
      groups: sudo
      append: true
  
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world
